blueprint:
  name: In Bed Sensor Automation
  description: >
    Sets in-bed state based on a presence sensor and distance from the sensor of a person.
    Runs every 5 minutes.
  domain: automation
  input:
    distance_sensor:
      name: Presence Target Distance Sensor
      selector:
        entity:
          domain: sensor
    min_distance:
      name: Minimum Distance
      default: 1
      selector:
        number:
          min: 0
          max: 10
          step: 0.1
    max_distance:
      name: Maximum Distance
      default: 8
      selector:
        number:
          min: 1
          max: 20
          step: 0.1
    area_id:
      name: Area
      description: Enter the area to target (e.g., 'bedroom').
      selector:
        area:

trigger:
  - platform: time_pattern
    minutes: "/5"

condition: []

action:
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input distance_sensor
            above: !input min_distance
            below: !input max_distance
        sequence:
          - service: oasira_b2b.set_in_bed_state
            data:
              area_id: !input area_id
              state: true
    default:
      - service: oasira_b2b.set_in_bed_state
        data:
          area_id: !input area_id
          state: false

mode: single